### ISSUE TITLE
Instance depuis starter : git config non mis à jour ?

### ISSUE THREAD

**Issue by galenskap** [canal-web/sites-factory#2]
J'ai fait : sudo ./magic.sh -gfrenchtaylor -fstarter -dstarter frenchtaylor

Le script a bien créé : /var/git/frenchtaylor 
mais : /var/www/vhosts/frenchtaylor.site.com/httpdocs/.git/config
a gardé /var/git/starter comme origin

Piste : la fonction prend le second argument (${2}) et non le paramètre de la lettre g ?

**Comment by galenskap** [comment]
-su: /home/deb/scripts/sites-factory/functions/new_git_init.sh: Permission denied

**Comment by Fwagra** [comment]
test
